# Generated by Django 6.1 on 2026-08-15 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('parking', 'No-Parking Violation'), ('air_pollution', 'Air Pollution'), ('water_pollution', 'Water Pollution'), ('land_dumping', 'Land / Dumping')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Confirmation'), ('unassigned', 'Unassigned'), ('accepted', 'Accepted by Officer'), ('dispatched', 'Officer En Route'), ('resolved', 'Resolved / Challan Issued'), ('rejected', 'Rejected / Invalid')], default='pending', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_class', models.CharField(choices=[('two_wheeler', 'Two-wheeler - ₹500'), ('car_suv', 'Car / SUV - ₹1,000'), ('commercial', 'Truck / Commercial - ₹2,000')], max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reporter_reward', models.DecimalField(decimal_places=2, help_text='15% of fine amount', max_digits=8)),
                ('officer_reward', models.DecimalField(decimal_places=2, help_text='15% of fine amount', max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challan', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='evidence_media/')),
                ('capture_sequence', models.IntegerField(default=1, help_text='1 for first photo, 2 for 10-min confirmation')),
                ('detected_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='reports.report')),
            ],
        ),
    ]
